### ISSUE TITLE
Add quantifiers in order to allow filtering applicant groups

### ISSUE THREAD

**Issue by athei** [0xbs/premade-applicants-filter#1]
I did a quick test and can verify than the add-on is working as intended. However, as expected there are some rough edges around applications that consist of multiple members. 

Correct me if I am wrong: The current behaviour is that each filter is applied to every member of a group and the group is only shown when each member satisfies the filter. One can argue that this **can** make sense for some filters (rio, level, region, ...) but for others it almost never makes any sense (class filters).

I think what would solve this problem without having to change the actual keywords is lifting the filter from propositions to predicates by introducing quantifiers.

**Example**
I look for the following: A demonhunter and a healer. I would formulate the following predicate:

`FA((dh or healer) and rio > 1800) and EX(rio > 2200) and members < 3`

`EX` and `FA` are the existential and the for all quantifier. `dh`, `healer`, `rio` are bound variables and `members` is  unbound (keyword does not exist yet). Brackets can be used to specify the scope of a quantifier.

You may noticed that we did not specify which variables are bound at the quantifier. This can be implicit. Every keyword that describes a member of a group (every keyword as of right now) is bound and must be quantified. Keywords that describe the group as a whole (`members`) are unbound and not allowed to be used under a quantifier.

**Comment by 0xbs** [comment]
It took me a while to wrap my head around your request, but I think I got some primitive first-order logic implemented as requested. Have a look at the README. Looking forward for your testing results.

**Comment by athei** [comment]
Sweet I will test tomorrow.

**Comment by athei** [comment]
Sorry that I never reported back. The commit with the quantifiers seems to brake all functionality. Meaning that no matter what I enter all applicants are still there. Nothing is filtered. I think we should discuss that further in #2.  Maybe we should close here.

**Comment by 0xbs** [comment]
Please continue to give feedback. I pushed version 0.4 which should fix the problems.
