### ISSUE TITLE
Rio and mprating not working

### ISSUE THREAD

**Issue by sjaakvdbrom** [0xbs/premade-applicants-filter#10]
Using the rio or mprating seem to do nothing right now. When I for example use `all("mprating > 2800")` I still see people that are `2600`. The same thing happens with `all("rio> 2800")`. 

This is happening on version 2.0.3 and a freshly updated RIO add-on.

**Comment by 0xbs** [comment]
Fixed version 2.1.1. I copied code from Premade Groups Filter without thinking but some keywords are different in this addon.
