### ISSUE TITLE
Not filtering OCE players.

### ISSUE THREAD

**Issue by gotex007** [0xbs/premade-applicants-filter#11]
It's not filtering OCE players and also spams me with errors like the one below.
```
`1802x PremadeApplicantsFilter/Main.lua:99: attempt to compare number with nil
[string "@PremadeApplicantsFilter/Main.lua"]:99: in function <PremadeApplicantsFilter/Main.lua:55>
[string "=[C]"]: ?
[string "=[C]"]: in function `LFGListUtil_SortApplicants'
[string "@FrameXML/LFGList.lua"]:1561: in function `LFGListApplicationViewer_UpdateResultList'
[string "@FrameXML/LFGList.lua"]:1376: in function `onEvent'
[string "@FrameXML/LFGList.lua"]:218: in function <FrameXML/LFGList.lua:139>

Locals:
applicants = <table> {
 1 = 16
}
model = <table> {
 enabled = true
 version = 1
 expression = "all("(not oce)")"
}
exp = "all("(not oce)")"
activeEntryInfo = <table> {
 comment = ""
 autoAccept = false
 requiredItemLevel = 0
 duration = 1799
 activityID = 466
 privateGroup = false
 isCrossFactionListing = true
 name = "|Ks1|k"
 playstyle = 1
 voiceChat = ""
 requiredHonorLevel = 0
}
(for index) = 1
(for limit) = 1
(for step) = -1
idx = 1
applicantID = 16
applicantInfo = <table> {
 numMembers = 1
 applicantID = 16
 comment = ""
 displayOrderID = 1
 isNew = true
 applicationStatus = "applied"
}
memberEnvs = <table> {
}
(for index) = 1
(for limit) = 1
(for step) = 1
memberIdx = 1
name = "Palenity-Sargeras"
class = "PALADIN"
localizedClass = "Paladin"
level = 70
itemLevel = 402.812500
honorLevel = 0
tank = false
healer = false
damage = true
assignedRole = "DAMAGER"
relationship = nil
dungeonScore = 1881
pvpItemLevel = 402.812500
bestDungeonScoreForEntry = <table> {
 bestRunLevel = 12
 finishedSuccess = true
 mapName = "Court of Stars"
 mapScore = 226
}
pvpRatingForEntry = nil
env = <table> {
 tank = false
 ilvl = 402.812500
 hlvl = 0
 rogue = false
 range = false
 pvpilvl = 402.812500
 hunter = false
 level = 70
 druid = false
 damage = true
 warrior = false
 paladin = true
 melee = true
 monk = false
 demonhunter = false
 dps = true
 warlock = false
 shaman = false
 priest = false
 heal = false
 mage = false
 healer = false
 myilvl = 405.687500
 deathknight = false
 guild = false
 friend = false
}
(*temporary) = nil
(*temporary) = <table> {
 DEATHKNIGHT = <table> {
 }
 WARRIOR = <table> {
 }
 PALADIN = <table> {
 }
 MAGE = <table> {
 }
 PRIEST = <table> {
 }
 SHAMAN = <table> {
 }
 WARLOCK = <table> {
 }
 DEMONHUNTER = <table> {
 }
 ROGUE = <table> {
 }
 DRUID = <table> {
 }
 MONK = <table> {
 }
 HUNTER = <table> {
 }
}
(*temporary) = "HUNTER"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = false
(*temporary) = "PALADIN"
(*temporary) = "attempt to compare number with nil"
PAF = <table> {
 NotEmpty = <function> defined @PremadeApplicantsFilter/Modules/Util.lua:34
 Dialog_Toggle = <function> defined @PremadeApplicantsFilter/Dialog/Dialog.lua:118
 GetModel = <function> defined @PremadeApplicantsFilter/Main.lua:51
 Dialog_ResetPosition = <function> defined @PremadeApplicantsFilter/Dialog/Dialog.lua:70
 TrimWhitespace = <function> defined @PremadeApplicantsFilter/Modules/Util.lua:37
 PutRaiderIOMetrics = <function> defined @PremadeApplicantsFilter/Plugins/RaiderIO.lua:48
 HandleSemanticError = <function> defined @PremadeApplicantsFilter/Modules/Expression.lua:36
 Table_UpdateWithDefaults = <function> defined @PremadeApplicantsFilter/Modules/Util.lua:23
 Dialog_InfoButton_OnEnter = <function> defined @PremadeApplicantsFilter/Dialog/HelpTooltip.lua:31
 GetNameRealmFaction = <function> defined @PremadeApplicantsFilter/Plugins/RaiderIO.lua:23
 L = <table> {
 }
 Dialog_OnLoad = <function> defined @PremadeApplicantsFilter/Dialog/Dialog.lua:43
 Dialog_UsePAF_OnClick = <function> defined @PremadeApplicantsFilter/Dialog/Dialog.lua:96
 UsePAFButton = UsePAFButton {
 }
 Dialog_ClearFocus = <function> defined @PremadeApplicantsFilter/Dialog/Dialog.lua:91
 GameTooltip_AddWhite = <function> defined @PremadeApplicantsFilter/Dialog/HelpTooltip.lua:23
 Dialog_OnMouseUp = <function> defined @PremadeApplicantsFilter/Dialog/Dialog.lua:81
 Dialog_OnMouseDown = <function> defined @PremadeApplicantsFilter/Dialog/Dialog.lua:77
 DoFilterSearchResults = <function> defined @PremadeApplicantsFilter/Main.lua:55
 Dialog_Expression_OnTextChanged = <function> defined @PremadeApplicantsFilter/Dialog/Dialog.lua:109
 DoesPassThroughFilter = <function> defined @PremadeApplicantsFilter/Modules/Expression.lua:40
 Dialog_Info`
```

**Comment by gotex007** [comment]
`2821x PremadeApplicantsFilter/Main.lua:94: attempt to index field '?' (a nil value)
[string "@PremadeApplicantsFilter/Main.lua"]:94: in function <PremadeApplicantsFilter/Main.lua:55>
[string "=[C]"]: in function `LFGListUtil_SortApplicants'
[string "@FrameXML/LFGList.lua"]:1561: in function `LFGListApplicationViewer_UpdateResultList'
[string "@FrameXML/LFGList.lua"]:1376: in function `onEvent'
[string "@FrameXML/LFGList.lua"]:218: in function <FrameXML/LFGList.lua:139>

Locals:
applicants = <table> {
 1 = 5
}
model = <table> {
 enabled = true
 version = 1
 expression = "all("not oce")"
}
exp = "all("not oce")"
activeEntryInfo = <table> {
 comment = ""
 autoAccept = false
 requiredItemLevel = 0
 duration = 1796
 activityID = 1060
 privateGroup = false
 isCrossFactionListing = false
 name = "|Ks1|k"
 questID = 70625
 voiceChat = ""
 requiredHonorLevel = 0
}
(for index) = 1
(for limit) = 1
(for step) = -1
idx = 1
applicantID = 5
applicantInfo = <table> {
 numMembers = 1
 applicantID = 5
 comment = ""
 displayOrderID = 1
 isNew = true
 applicationStatus = "applied"
}
memberEnvs = <table> {
}
(for index) = 1
(for limit) = 1
(for step) = 1
memberIdx = 1
name = "Cenderia-Alleria"
class = "EVOKER"
localizedClass = "Evoker"
level = 70
itemLevel = 340.812500
honorLevel = 0
tank = false
healer = true
damage = false
assignedRole = "HEALER"
relationship = nil
dungeonScore = 0
pvpItemLevel = 340.812500
bestDungeonScoreForEntry = <table> {
 bestRunLevel = 0
 finishedSuccess = false
 mapName = ""
 mapScore = 0
}
pvpRatingForEntry = nil
env = <table> {
 tank = false
 guild = false
 hlvl = 0
 dps = false
 friend = false
 pvpilvl = 340.812500
 ilvl = 340.812500
 healer = true
 myilvl = 334
 level = 70
 heal = true
 damage = false
}
(*temporary) = nil
(*temporary) = "EVOKER"
(*temporary) = "EVOKER"
(*temporary) = "EVOKER"
(*temporary) = 340.875000
(*temporary) = 340.875000
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
PAF = <table> {
 NotEmpty = <function> defined @PremadeApplicantsFilter/Modules/Util.lua:34
 Dialog_Toggle = <function> defined @PremadeApplicantsFilter/Dialog/Dialog.lua:118
 GetModel = <function> defined @PremadeApplicantsFilter/Main.lua:51
 Dialog_ResetPosition = <function> defined @PremadeApplicantsFilter/Dialog/Dialog.lua:70
 TrimWhitespace = <function> defined @PremadeApplicantsFilter/Modules/Util.lua:37
 PutRaiderIOMetrics = <function> defined @PremadeApplicantsFilter/Plugins/RaiderIO.lua:48
 HandleSemanticError = <function> defined @PremadeApplicantsFilter/Modules/Expression.lua:36
 Table_UpdateWithDefaults = <function> defined @PremadeApplicantsFilter/Modules/Util.lua:23
 Dialog_InfoButton_OnEnter = <function> defined @PremadeApplicantsFilter/Dialog/HelpTooltip.lua:31
 GetNameRealmFaction = <function> defined @PremadeApplicantsFilter/Plugins/RaiderIO.lua:23
 L = <table> {
 }
 Dialog_OnLoad = <function> defined @PremadeApplicantsFilter/Dialog/Dialog.lua:43
 Dialog_UsePAF_OnClick = <function> defined @PremadeApplicantsFilter/Dialog/Dialog.lua:96
 UsePAFButton = UsePAFButton {
 }
 Dialog_ClearFocus = <function> defined @PremadeApplicantsFilter/Dialog/Dialog.lua:91
 GameTooltip_AddWhite = <function> defined @PremadeApplicantsFilter/Dialog/HelpTooltip.lua:23
 Dialog_OnMouseUp = <function> defined @PremadeApplicantsFilter/Dialog/Dialog.lua:81
 Dialog_OnMouseDown = <function> defined @PremadeApplicantsFilter/Dialog/Dialog.lua:77
 DoFilterSearchResults = <function> defined @PremadeApplicantsFilter/Main.lua:55
 Dialog_Expression_OnTextChanged = <function> defined @PremadeApplicantsFilter/Dialog/Dialog.lua:109
 DoesPassThroughFilter = <function> defined @PremadeApplicantsFilter/Modules/Expression.lua:40
 Dialog_InfoButton_OnLeave = <function> defined @PremadeApplicantsFilter/Dialog/HelpTooltip.lua:79
 GameTooltip_AddDoubleWhite = <function> defined @PremadeApplicantsFilter/Dialog/HelpTooltip.lua:27
 HandleSyntaxError = <function> defined @PremadeApplicantsFilter/Modules/Expression.lua:32
 PutPremadeRegionInfo = <function> defined @PremadeApplicantsFilter/Plugins/PremadeRegions.lua:23
 C = <table> {
 }
 Dialog_SetUpUsePAFCheckbox = <function> defined @`

**Comment by 0xbs** [comment]
Thanks for the report, addon was missing support for evokers. And yes, it's a shame that you're the first one reporting it and also that I did not yet fix it! Very rarely craeting groups myself.
