### ISSUE TITLE
Can't seem to get PAF to work

### ISSUE THREAD

**Issue by dvhaldane** [0xbs/premade-applicants-filter#2]
I can't seem to get PAF to work.  Am I doing something wrong?  I've entered some arbitrarily large ilvl to remove applicants from the list, but they still show up even after re-queueing.  I've also tried reinstalling the mod.

![image](https://user-images.githubusercontent.com/6241606/76167442-ead81200-6123-11ea-8a03-103e19c2720d.png)

**Comment by dvhaldane** [comment]
Guess I could use my brain a bit and actually go hunting for errors... here's what I've found.

Message: ...ddOns\PremadeApplicantsFilter\Modules\Expression.lua:59: attempt to index global 'PGF' (a nil value)
Time: Sun Mar  8 10:05:03 2020
Count: 199
Stack: ...ddOns\PremadeApplicantsFilter\Modules\Expression.lua:59: attempt to index global 'PGF' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:733: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:693>
[string "=[C]"]: ?
[string "@Interface\AddOns\PremadeApplicantsFilter\Modules\Expression.lua"]:59: in function `DoesPassThroughFilter'
[string "@Interface\AddOns\PremadeApplicantsFilter\Main.lua"]:118: in function <Interface\AddOns\PremadeApplicantsFilter\Main.lua:42>
[string "=[C]"]: in function `LFGListUtil_SortApplicants'
[string "@Interface\FrameXML\LFGList.lua"]:1298: in function `LFGListApplicationViewer_UpdateResultList'
[string "@Interface\FrameXML\LFGList.lua"]:1144: in function `onEvent'
[string "@Interface\FrameXML\LFGList.lua"]:213: in function <Interface\FrameXML\LFGList.lua:130>

Locals: errMsg = "...ddOns\PremadeApplicantsFilter\Modules\Expression.lua:59: attempt to index global 'PGF' (a nil value)"
tsmErrMsg = nil
oldModule = nil
private = <table> {
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:514
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:132
 hitInternalError = false
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:295
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:495
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:480
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:488
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:328
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:380
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:456
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:297
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by dvhaldane** [comment]
Rolled version back to 0.2-beta and found that this works as expected.  Likely related to https://github.com/0xbs/premade-applicants-filter/issues/1.  After changing references of PGF to PAF in Expression.lua, found that there were errors thrown from this line https://github.com/0xbs/premade-applicants-filter/blob/master/Main.lua#L90

**Comment by 0xbs** [comment]
That's why I am desperately waiting for feedback from you guys! I rarely create a group which makes it really hard for me to test the addon. I sometimes beg some people in trade chat to join my test group, but coding under time pressure is not fun.

Alright, I fixed two major bugs I did not notice when creating version 0.3. Anyway, please test the new version 0.4!

**Comment by dvhaldane** [comment]
Spot tested the application using the all() expression against rio, riomythicprogress, rionormalprogress, class, and spec filters.  These worked as expected for single applicants as well as group applicants.  

Tested the some() expression against ilvl filters which also appears to work as expected for single applicants as well as group applicants.

Thanks for the quick fix.  

In regard to testing, a helpful tip... just create a M+ dungeon listing for a 15 Freehold.  You'll have applicants out your ears.
