### ISSUE TITLE
1.0.0 does not seem to work in Shadowlands

### ISSUE THREAD

**Issue by sjaakvdbrom** [0xbs/premade-applicants-filter#3]
When I use the 1.0.0 version I cannot seem to get it to work anymore. When I revert back to 0.4 it does kind of work, but not with raider.io (probably because of a new API or such). The 1.0.0 version does not seem to respond to anything anymore, even if you write gibberish it wil not give you an error stating it is not valid. 

Also in your screenshot on curse there seems to be a different syntax to what you type. In your screenshot there also seem to be different examples. For instance there is no all("") anymore in the screenshot. This might be new syntax but this is not reflected in the readme either. And in the 1.0.0 version I use the Filter Expressions box is still the same as 0.4, not the one like in the screenshot.

**Comment by 0xbs** [comment]
Last time I checked, the addon did work as expected. I know that this addon is not getting as much attention from me as PGF since I rarely open groups myself and don‘t have a level 60 character, but will try to check the next days.

**Comment by 0xbs** [comment]
You are right, there was a copy paste error in the code. Is fixed now, thank you for your bug report!

**Comment by 0xbs** [comment]
Project description on CurseForge has been updated. Screenshots are still the same though.
