### ISSUE TITLE
Can't properly search for servers.

### ISSUE THREAD

**Issue by gotex007** [0xbs/premade-applicants-filter#4]
The syntax doesn't seem to like LA and CHI servers. The listed syntax on the page must be outdated or something as well as the addon.

**Comment by gotex007** [comment]
all("(la or chi) and (rio > 600 or riomain > 800)")

This kind of setup is what I was using, for example. I tried using usp, usm, etc but those aren't the names of the servers in the addon so nothing gets shown at all.

**Comment by 0xbs** [comment]
You are right, premade region integration was outdated. Thanks for reporting!

**Comment by gotex007** [comment]
It's still showing Brazil and Mexico servers when I do the same search as above.
