### ISSUE TITLE
Blizzard score support

### ISSUE THREAD

**Issue by athei** [0xbs/premade-applicants-filter#5]
With the recent 9.1 patch Blizzard introduced its own scoring system. I expect it to replace the raider.io scoring system. Would be nice to have a filter for it if possible.

**Comment by 0xbs** [comment]
Thank you for bringing this to my attention. I am currently a bit out of WoW, but will continue to support the addon and this sounds like a great extension if possible. Will look into this in a week as I am currently on holidays.

**Comment by 0xbs** [comment]
I pushed version 1.1.0-alpha which provides five new keywords to get the Blizz rating values. Feel free testing it and reporting back on me. Stable release should come next week.

**Comment by 0xbs** [comment]
Version 1.1.1 is now released.
